### PR TITLE
AttributeError: 'int' object has no attribute 'lower'

### PR DESCRIPTION
**Pull request by btall**
Caused by a call directly with the result from the method getgroupmembers.

### CODE REVIEW

**Comment by Itxaka** [comment]
Probably won't pass the tests due to basestring not available on python3, good catch anyway!

**Comment by btall** [comment]
Yet it is managed [here](https://github.com/btall/pyapi-gitlab/blob/fix/addprojectmember/gitlab/__init__.py#L15), right?

**Comment by Itxaka** [comment]
Indeed! I even forgot about it. Thanks for the patch!

**Comment by btall** [comment]
Your welcome! thanks for the module and your merge :smile:

**Pull request merged**
