### PR TITLE
feat: Enable deploy keys for a project

### PR DESCRIPTION
**Pull request by sijis**
Adding ability to add deploy keys.

### CODE REVIEW

**Comment by Sudo-Kid** [comment]
This PR is in response to issue https://github.com/pyapi-gitlab/pyapi-gitlab/issues/216.

**Comment by Sudo-Kid** [comment]
Have you been able to checkout the new unittests yet. If not I don't mind coding them up to get your PR in.

**Comment by sijis** [comment]
@the-kid89 I got the most of the unittests working with the exception of this one `test_enable_deploy_key_exception`.

I've pushed everything I got so far.

**Comment by Sudo-Kid** [comment]
I still sometime make that syntax mistake when using `assertRaises()`. What you will want to do on line 71 of `test_deploy_keys.py` is update it like so `self.assertRaises(HttpError, self.gitlab.enable_deploy_key, 5, 2)`. The `assertRaises` takes all the function/method arguments as arguments itself.

**Comment by sijis** [comment]
Ahh. Thanks!

Fixed.

**Pull request merged**
