### PR TITLE
Feature pagination for getGroups and getUsers

### PR DESCRIPTION
**Pull request by samrocketman**
`Gitlab.getGroups` and `Gitlab.getUsers` now has pagination.  I tested it against my own instance of GitLab 6 and it works.  I just set the `per_page=1` and iterated through `page` to test it.  I'll see what other functions I can add pagination to as well.

I also updated some of the pydocs.

### CODE REVIEW

**Comment by samrocketman** [comment]
This resolves issue #20

**Comment by samrocketman** [comment]
I tested `Gitlab.getSshKeys`.  It does not support pagination at all so no need to implement it there.

**Comment by samrocketman** [comment]
`getIssues` and `getProjectIssues` might need pagination as well.  I'll have to create a few test cases for it and report back if they pan out.

**Comment by samrocketman** [comment]
With this I believe I have covered pagination for all possible use cases in this API library.  Let me know if you think I missed anything and I'll update the pull request.

**Comment by Itxaka** [comment]
Thanks!

**Pull request merged**
